phrase:
  project_id: d3e6ed1211664e5e232a5d95b67580e3
  push:
    sources:
    - file: ./<locale_name>/page1.json
      params:
        file_format: i18next_4
        tags: page1
    - file: ./<locale_name>/page2.json
      params:
        file_format: i18next_4
        tags: page2
    - file: ./<locale_name>/page3.json
      params:
        file_format: i18next_4
        tags: page3
    - file: ./<locale_name>/newPage.json
      params:
        file_format: i18next_4
        tags: newPage
  pull:
    targets:
    - file: ./<locale_name>/page1.json
      params:
        file_format: i18next_4
        tags: page1
    - file: ./<locale_name>/page2.json
      params:
        file_format: i18next_4
        tags: page2
    - file: ./<locale_name>/page3.json
      params:
        file_format: i18next_4
        tags: page3
    - file: ./<locale_name>/newPage.json
      params:
        file_format: i18next_4
        tags: newPage
